# Generated by Django 5.1.7 on 2025-04-07 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0009_alter_profile_avatar_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='picture',
        ),
        migrations.AddField(
            model_name='post',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='postpic/'),
        ),
        migrations.AddField(
            model_name='post',
            name='pic_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
