# Generated by Django 5.1.7 on 2025-04-08 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0010_remove_post_picture_post_pic_post_pic_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='pic_url',
        ),
        migrations.AlterField(
            model_name='post',
            name='pic',
            field=models.URLField(blank=True, default='https://ichef.bbci.co.uk/ace/standard/2560/cpsprodpb/b2d0/live/d4d933e0-8a17-11ef-bfd3-790fcba1cccf.jpg', null=True),
        ),
    ]
